export enum AxiosErrorCodes {
  ERR_BAD_REQUEST = 'ERR_BAD_REQUEST',
  ERR_NOT_FOUND = 'ERR_NOT_FOUND',
  ERR_REQUEST_TIMEOUT = 'ERR_REQUEST_TIMEOUT',
  ERR_TOO_MANY_REQUESTS = 'ERR_TOO_MANY_REQUESTS',
}
